### ISSUE TITLE
其实可以反过来做成Android和iOS端

### ISSUE THREAD

**Issue by redstoneleo** [bitepeng/b0pass#10]
其实可以反过来做成Android和iOS端，这样就只需要打包两个平台了（而不是现在的三大桌面平台），类似于airdroid和快传这种，这样子的好处就是可以在PC上的网页端下载手机端的相册之类的了。
airdroid和快传的问题在于用户体验不够好，比如扫码后还需要点击按钮确认登陆，比较麻烦。
如果决定做Android和iOS端的话我可以帮忙设计提升易用性哦！

**Comment by bitepeng** [comment]
你好，非常感谢你的建议和思考，这的确也是一种方向。我本人在安卓，ios原生开发方面经验不足，如果可以，我们可以尝试做一个分支版本。

**Comment by redstoneleo** [comment]
我主要玩Python ，完全不会APP开发。
提升产品易用性这方面我倒是比较有想法的。

**Comment by bitepeng** [comment]
嗯，后续我做个跨平台app也可以。

**Comment by redstoneleo** [comment]
谢谢！到时候要提升产品易用性的帮助的话可以在这个issue里告诉我

**Comment by bitepeng** [comment]
OK

**Comment by bitepeng** [comment]
手机app已发布
