### ISSUE TITLE
从手机下载了一个64G的大文件，windows上的应用程序直接崩溃了

### ISSUE THREAD

**Issue by weixiupc** [bitepeng/b0pass#11]
从手机下载了一个64G的大文件，windows上的应用程序直接崩溃了，可以做个安卓版的，然后从电脑上传到安卓手机试试

**Comment by bitepeng** [comment]
我测试最大的文件是2.5G，的确没测试过64G这么大的。有没有报错信息呢？

**Comment by bitepeng** [comment]
最大上传多大文件，还是取决于你的服务器内存大小的。这个错误提示内存占满了。这个软件的主要目的还是局域网文件传输，一般生活中的大文件30M-3G应该是没问题。

**Comment by bitepeng** [comment]
内存优化版已经发布 https://github.com/bitepeng/b0pass/releases/tag/v0.1.6
