### ISSUE TITLE
On The Mac OS Catalina Unexpected exit

### ISSUE THREAD

**Issue by huangweiboy2** [bitepeng/b0pass#12]
在MacOS Catalina上打开了一次之后就意外退出了

**Comment by bitepeng** [comment]
建议安装 b0pass_mac_cli 命令行版本，然后自行在浏览器输入127.0.0.1:8899开启界面。

**Comment by bitepeng** [comment]
内存优化版已经发布 https://github.com/bitepeng/b0pass/releases/tag/v0.1.6
