### ISSUE TITLE
增加一个上传文件后，执行指定命令的功能　

### ISSUE THREAD

**Issue by lvbuwei** [bitepeng/b0pass#14]
比如，一群人在办公室开会，某个人的电脑联接到投影仪，运行本程序，显示出二维码，大家的手机扫描一下后，不同人手机上传的照片，如果是ＰＮＧ或者ＪＰＧ的，服务器在接收后，可以显示出这个文件，具体调用哪个程序显示，可以由电脑配置文件指定。比如，我用ubuntu,我就会调用

eog -w filepath
这样的话，大家可开会时，可以方便的把工作中拍到的照片在会议上方便的实时共享和讨论。
可以在配置文件中指定，比如
jpg,png=eog -w %f
这样的格式

作者有ＱＱ群或者微信群不，我们这些对这个软件爱好的人，可以加进去讨论学习。

**Comment by lvbuwei** [comment]
还发现一个小问题，图片不能多张往上传。好希望能支持这个功能啊。

**Comment by bitepeng** [comment]
@lvbuwei 关于第一个设想，我的开发计划是使用长连接，让上传之后自动通知各端。不能多选的问题应该是微信浏览器的限制，可以在手机上使用qq浏览器等第三方浏览器。

**Comment by lvbuwei** [comment]
不是，你理解错的我意思了，您这个想法，是让各个手机端可以看到新上传的问题，我的想法是通过上传的文件，服务端调用显示图像的软件，自动显示这个最新上传的文件，在这特定的场景下很有用。
比如，销售人员每天开晨会，大家把昨天拍的照片一上传，投影仪上就会显示出这个拍的内容，然后第二个再上传照片，大家在投影仪上，同时看第二个照片反应的问题，类似这种场景。

**Comment by bitepeng** [comment]
@lvbuwei 好的，了解了

**Comment by bitepeng** [comment]
v0.1.8 使用另一种方式支持此场景。https://gitee.com/b0cloud/b0pass/releases 
新增 传输文本功能，多端共享
新增 点击在主电脑打开文件根目录功能，支持远程打开
新增 点击在主电脑打开图片、视频、文件、目录功能，在手机上打开相当于“投屏”
优化 文件显示界面

**Comment by lvbuwei** [comment]
太感谢了。

**Comment by lvbuwei** [comment]
确实好用，作者太走心了，您建个QQ群或者微信群吧。大家好给百灵快传添砖加瓦。
