### ISSUE TITLE
ssr代理与b0pass是否冲突呢？

### ISSUE THREAD

**Issue by ariagecheney** [bitepeng/b0pass#20]
请教一下，使用ssr会占用127.0.0.1:1080，然后如果此时开启b0pass，浏览器访问127.0.0.1:8899则会提示”localhost阻止了该访问，请（按提示）设置代理。“

**Comment by bitepeng** [comment]
请在你的代理里面设置例外

**Comment by bitepeng** [comment]
请在你的代理里面设置例外
