### ISSUE TITLE
安卓到PC大文件700M上传总中断出错

### ISSUE THREAD

**Issue by nimingzhe7** [bitepeng/b0pass#29]
安卓类原生 Los17.1  X浏览器, 电脑win7, 百灵0.1.9. 

500兆以下文件上传电脑均一次成功,  700兆的文件上传到最后5%左右开始没有反应,  过一会就异常中断,  试了四五次都是一样出错,  从来没有成功过

另外一个小问题:  Apk安装包从电脑取回手机时,  总是自动改名后缀为zip,  (每次都要手工改回来)  不知道是bug呢，还是出于什么考虑?

**Comment by bitepeng** [comment]
新版本已发布，问题已解决
