### ISSUE TITLE
路径包含空格时打开文件夹出错

### ISSUE THREAD

**Issue by john2021wick** [bitepeng/b0pass#32]
exe文件放在包含空格的目录时，例如“Program Files”
电脑打开目录会报错

/api/openurl?url=D:/Program%20Files
提示找不到目录“D:/Program”

更新：
实测最无脑的解决方法是修改"cmd /c start " 为 "cmd /c start explorer "

**Comment by bitepeng** [comment]
新版本已发布，问题已解决

**Comment by bitepeng** [comment]
建议把百灵快传放在一个没有空格路径的目录里。
