### ISSUE TITLE
可以把手机扫码地方的地址解析为当前浏览器的地址吗？

### ISSUE THREAD

**Issue by sunup2015** [bitepeng/b0pass#36]
作者，您好！
请问可以把手机扫码地方的地址让显示为当前浏览器的 域名或IP+端口 吗？并且二维码的解析地址也为当前 域名或ip+端口号呢？
![image](https://user-images.githubusercontent.com/30277413/197373936-e3cd218d-f7fa-4dbb-80a3-4a4775f10269.png)

**Comment by bitepeng** [comment]
新版本已发布，问题已解决。你可以通过配置config.ini达到效果。
