### ISSUE TITLE
为什么软件双击后不能启动？

### ISSUE THREAD

**Issue by maicikao** [bitepeng/b0pass#37]
软件前段时间可以正常启动，现在出现弹出命令行后就直接消失
![image](https://user-images.githubusercontent.com/86543120/224614892-24368a66-9af7-4a92-90c3-96b78d9b04a9.png)

**Comment by maicikao** [comment]
任务管理器里面也一起消失了，像是崩掉了

**Comment by theyyzz** [comment]
好像是win11不行~~

**Comment by maicikao** [comment]
> 好像是win11不行~~

我是win10，突然就不能用了，发现不能用的前一天还可以用T_T

**Comment by risetek-wangxu** [comment]
遇到一样的情况了，win10，但是应该是系统没有关系，我把chrome浏览器卸载后就可以用了，不知道了是chrome自动更新了还是什么原因

**Comment by bitepeng** [comment]
新版本已发布，问题已解决
