### ISSUE TITLE
win10闪退

### ISSUE THREAD

**Issue by zhuzifei** [bitepeng/b0pass#38]

**Comment by zhuzifei** [comment]
找到了错误信息：websocket.Dial ws://127.0.0.1:1900/devtools/browser/19ebf7cc-598b-4b79-9313-271ba2b5a14b: bad status

之前是好用的后来没有修改过设置，肯能是有些规则发生了变化

**Comment by baozugong** [comment]
我也是这样的情况，不知道跟win10更新了有没有关系，之前能用的，最近就闪退了

**Comment by woshitoutouge** [comment]
闪退+1

**Comment by JiangHao12138** [comment]
闪退+1，话说作者是放弃这个项目了么

**Comment by glq1218** [comment]
![image](https://github.com/bitepeng/b0pass/assets/92007882/f8361d19-a6eb-4b18-9234-e3d86051c8dd)
出现这个提示之后就会闪退

**Comment by night-candle** [comment]
在 main.go 56行 `lorca.New()` 函数中添加参数 "--remote-allow-origins=*" 后重新编译打包即可
```
ui, err := lorca.New(..., "--remote-allow-origins=*")
```

**Comment by DazzlingGalaxy** [comment]
> 卸载 Chrome，使用其他浏览器； 或在 main.go 56行 `lorca.New()` 函数中添加参数 "--remote-allow-origins=*" 后重新编译打包
> 
> ```
> ui, err := lorca.New(..., "--remote-allow-origins=*")
> ```

非常感谢！终于又能用了！

**Comment by night-candle** [comment]
PS 作者可能暂停了对项目的维护，[这里](https://github.com/night-candle/b0pass/releases/tag/v0.1.9.1)提供已编译的 win 可执行文件，希望能有帮助

**Comment by shimakotodo** [comment]
> PS 作者可能暂停了对项目的维护，[这里](https://github.com/night-candle/b0pass/releases/tag/v0.1.9.1)提供已编译的 win 可执行文件，希望能有帮助

感谢分享！最近edge更新就不能用原版了，所幸找到你的编译版，真是感谢。

**Comment by leeseean** [comment]
win11也闪退

**Comment by night-candle** [comment]
> win11也闪退

解决方法同上，问题由 Chrome 更新引起，与系统无关

**Comment by zhuzifei** [comment]
> PS 作者可能暂停了对项目的维护，[这里](https://github.com/night-candle/b0pass/releases/tag/v0.1.9.1)提供已编译的 win 可执行文件，希望能有帮助

非常感谢

**Comment by bitepeng** [comment]
新版本已发布，问题已解决
