### ISSUE TITLE
请问能否发布一个Linux amd64版？

### ISSUE THREAD

**Issue by itfanr** [bitepeng/b0pass#4]

**Comment by bitepeng** [comment]
你好，发布 linux 版本就在开发路线图中，估计就在这几天发布。

**Comment by bitepeng** [comment]
刚刚打包 linux amd64 版本 https://gitee.com/b0cloud/b0pass/releases

**Comment by bitepeng** [comment]
今天打包的linux版本还有点问题，这个任务先打开。

**Comment by bitepeng** [comment]
昨日晚间已经发布。
