### ISSUE TITLE
app 端上传文件会修改原始文件名

### ISSUE THREAD

**Issue by taerc** [bitepeng/b0pass#46]
尝试了一下，非常好用

## 现象
* 从 pc 上上传保留了原始文件名
* 从 手机上传文件会修改原始文件名
## 期望
* 手机端和pc端不修改原始文件名

## TODO
* clone 了一份代码，准备跟踪，发现是在前端代码已经修改了文件名，能修复一下么？

**Comment by bitepeng** [comment]
测试了一下手机上传文件，名称并没有改变，情况没有重现。

**Comment by taerc** [comment]
iPhone 的图片名会变，可能是因为 iPhone 的图片格式问题导致；Android 保留原始文件名.
